face_att/urls.py
from django.contrib import admin
from django.urls import path,include

from reg_sign_in_out import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    # path('',hqviews.index,name="index"),
    path('admin/', admin.site.urls),
    path('',include('hq.urls'),name="hq"),
    path('',include('reg_sign_in_out.urls'),name="reg_sign_in_out"),
    path('logout/',views.user_logout,name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html', email_template_name='email_template.html'),name='reset_password'),
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),
]

hq/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from face_att import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "hq"

urlpatterns = [
    path('new_entry/<id>-<name>/',views.capImg,name='capImg'),
    path('new_entry/',views.new_entry,name='new_entry'),
    path('profile/<id>/',views.profile,name='profile'),
    path('delete/<pid>/<imgid>/',views.deleteimg,name='deleteimg'),
    path('search/',views.search,name='search'),
    path('startstream/',views.startstream,name='startstream'),
    path('sync/',views.sync,name='sync'),
    path('streamer/',views.streamer,name='streamer'),
    path('delete-<id>/',views.delete_entry,name='delete_entry'),
    path('edit-<id>/',views.edit_entry,name='edit_entry'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

templates/base.html
<!DOCTYPE html>
{% load static %}
<html > 
    <head>
        <title>Facial Recognition System</title>
        <link
        rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        
        {% block head_block %}
          
        {% endblock head_block %}
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap" rel="stylesheet">
        
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Facial Recognition System</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'hq:new_entry' %}">Add User</a>
                    <a class="nav-item nav-link" href="{% url 'admin:index'%}">Admin Access</a>
                    <a class="nav-item nav-link" href="{% url 'hq:streamer'%}">Start Stream</a>
                    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'hq:search' %}">          
                        <label class="nav-item nav-link" for="query" >Search Record:</label>
                        <input name="q" value="{{request.GET.q}}" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="nav-item nav-link" type="submit"> Search </button>
                    </form>
                    {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'logout' %}">  Logout</a>   
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'reg_sign_in_out:user_login' %}">   Login</a>
                    {% endif %}
                  <!-- <a class="nav-item nav-link disabled" href="#">Disabled</a> -->
                </div>
              </div>
          </nav>
   
          {% block body_block %}
          
          {% endblock body_block %}

          
<script src="/static/js/jquery-3.5.1.js" ></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{% static 'js/jquery.waypoints.js' %}"></script>
<script src="{% static 'js/infinite.js' %}"></script>
    </body>
</html>

templates/email_template.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://mission-vidya.herokuapp.com{% url 'password_reset_confirm' uidb64=uid token=token %}

templates/password_reset.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	{% block head_block %}
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
<style>
    img {
  border-radius: 8px;
  height: auto;
  width: 800px;
}
.wrap-login-custom {
  width: 1000px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
</style>
<link rel="stylesheet" type="text/css" href="/static/index.css">


{% csrf_token %}
{% endblock head_block %}
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../../static/images/bg-01.jpg');">
			<div class="wrap-login-custom  p-l-55 p-r-55 p-t-65 p-b-54">
                {% csrf_token %}
				<div class='container'>
				<h3 style="color: darkgrey;" class='jumbotron'>Password reset</h3>

				<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

				<div class='container' id='color'>
					<form method="post">
						{% csrf_token %}
						{{form|crispy}}
						<button class='text-center btn btn-light' type="Submit" name="Send email">Send Email</button>
					</form>
				</div>
				</div>
			</div>
		</div>
	</div>
	
	{% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>

templates/password_reset_complete.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	{% block head_block %}
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
<style>
    img {
  border-radius: 8px;
  height: auto;
  width: 800px;
}
.wrap-login-custom {
  width: 1000px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
</style>
<link rel="stylesheet" type="text/css" href="/static/index.css">
<style>
    #color,p{
      color: darkgrey; !important
    }
  </style>
{% endblock head_block %}
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../../static/images/bg-01.jpg');">
			<div class="wrap-login-custom  p-l-55 p-r-55 p-t-65 p-b-54">
        <h3 style="color: darkgrey;">Password reset complete</h3>

        <p>Your password has been set. You may go ahead and log in now.</p>
			</div>
		</div>
	</div>
	
	{% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>

templates/password_reset_confirm.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	{% block head_block %}
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
<style>
    img {
  border-radius: 8px;
  height: auto;
  width: 800px;
}
.wrap-login-custom {
  width: 1000px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
</style>

<link rel="stylesheet" type="text/css" href="/static/index.css">


{% endblock head_block %}
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../../static/images/bg-01.jpg');">
			<div class="wrap-login-custom  p-l-55 p-r-55 p-t-65 p-b-54">
                {% csrf_token %}
                <div class='container'>
                <h3 class='jumbotron'>Enter new password</h3>

                <p>Please enter your new password twice so we can verify you typed it in correctly.</p>

                <form style='margin-left:10px; max-width: 300px;' method="post" id='color'>

                  {% csrf_token %}
                  {{form|crispy}}
                  <input type="Submit" type='button' class='btn btn-success' name="Update Password">
                  
                </form>
                </div>
			</div>
		</div>
	</div>
	
	{% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>

templates/password_reset_sent.html
{% extends "base.html" %}
{% load static %}
{% block head_block %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}"> -->
<link rel="stylesheet" type="text/css" href="/static/index.css">

  <style>
    #color{
      color: darkgrey; !important
    }
  </style>
{% endblock head_block %}

{% block body_block %}

<div class='container'>
<h3 class='jumbotron'>Password Reset Sent</h3>


<p id='color'>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p id='color'>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>
</div>
{% endblock %}