face_att/urls.py
from django.contrib import admin
from django.urls import path,include

from reg_sign_in_out import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt

urlpatterns = [
    # path('',hqviews.index,name="index"),
    path('admin/', admin.site.urls),
    path('',include('hq.urls'),name="hq"),
    path('',include('reg_sign_in_out.urls'),name="reg_sign_in_out"),
    path('logout/',views.user_logout,name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html', email_template_name='email_template.html'),name='reset_password'),
    path('password-reset/sent/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_sent.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',success_url = reverse_lazy('reg_sign_in_out:user_login')),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html',),name='password_reset_complete'),
]

hq/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from face_att import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "hq"

urlpatterns = [
    path('new_entry/<id>-<name>/',views.capImg,name='capImg'),
    path('new_entry/',views.new_entry,name='new_entry'),
    path('profile/<id>/',views.profile,name='profile'),
    path('delete/<pid>/<imgid>/',views.deleteimg,name='deleteimg'),
    path('search/',views.search,name='search'),
    path('startstream/',views.startstream,name='startstream'),
    path('sync/',views.sync,name='sync'),
    path('streamer/',views.streamer,name='streamer'),
    path('delete-<id>/',views.delete_entry,name='delete_entry'),
    path('edit-<id>/',views.edit_entry,name='edit_entry'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

hq/models.py
from django.db import models
#from django.contrib.auth.models import User
import os
from fractions import Fraction
# from camera_imagefield import CameraImageField


class Person(models.Model):

    #team_user = models.OneToOneField(User,on_delete=models.CASCADE)
    id_number = models.CharField(max_length=128,blank=False,unique=True)
    name = models.CharField(max_length=50, blank=False)
    #team_email_id = models.EmailField(max_length=254,blank=False)
    #paid = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name



def get_upload_path(instance, filename):
    return os.path.join(
      "%s" % instance.person.id_number, filename)


class PersonImage(models.Model):
    person = models.ForeignKey(Person,on_delete=models.CASCADE)
    pictures = models.ImageField(upload_to=get_upload_path,blank=False)
    # pictures = CameraImageField(aspect_ratio=Fraction(16, 9))
    # picture = CameraField(upload_to=get_upload_path, blank=True)

    def __str__(self):
        return self.person.id_number

class PersonBuffer(models.Model):

    id_number = models.CharField(max_length=128,blank=False,unique=True)
    name = models.CharField(max_length=50, blank=False)

    def __str__(self):
        return "{} - {}".format(self.name,self.id_number)

hq/forms.py
from django import forms
from hq.models import Person, PersonImage,PersonBuffer

class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('id_number','name')

class PersonImageForm(forms.ModelForm):

    class Meta:
        model = PersonImage
        fields = ('pictures',)

class PersonBufferForm(forms.Form):
    list_of_people = forms.ModelChoiceField(queryset=PersonBuffer.objects.all().order_by('name'),to_field_name="id_number")
    class Meta:
        model = Person
        fields = ('list_of_people',)
        

hq/views.py
from django.shortcuts import render
import ocvgui
import tkinter
from . import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import os
from .models import Person, PersonImage,PersonBuffer
from face import face
import urllib, json


from django.views.decorators import gzip
from django.http import StreamingHttpResponse,HttpResponseServerError
from django.contrib.auth.decorators import login_required


from CONFIG import *
import cv2
import numpy as np
import mmap
from posix_ipc import Semaphore, SharedMemory, ExistentialError
from ctypes import sizeof, memmove, addressof, create_string_buffer
from time import sleep

from structures import MD

md_buf = create_string_buffer(sizeof(MD))


class ShmRead:
    def __init__(self, name):
        self.shm_buf = None
        self.md_buf = None

        while not self.md_buf:
            try:
                print("Waiting for MetaData shared memory is available.")
                md_region = SharedMemory(name + '-meta')
                self.md_buf = mmap.mmap(md_region.fd, sizeof(MD))
                md_region.close_fd()
                sleep(1)
            except ExistentialError:
                sleep(1)

        self.shm_name = name
        self.sem = Semaphore(name, 0)

    def get(self):
        md = MD()

        self.sem.acquire()
        md_buf[:] = self.md_buf
        memmove(addressof(md), md_buf, sizeof(md))
        self.sem.release()

        while not self.shm_buf:
            try:
                print("Waiting for Data shared memory is available.")
                shm_region = SharedMemory(name=self.shm_name)
                self.shm_buf = mmap.mmap(shm_region.fd, md.size)
                shm_region.close_fd()
                sleep(1)
            except ExistentialError:
                sleep(1)

        self.sem.acquire()
        f = np.ndarray(shape=(md.shape_0, md.shape_1, md.shape_2), dtype='uint8', buffer=self.shm_buf)
        self.sem.release()
        return f

    def release(self):
        self.md_buf.close()
        self.shm_buf.close()





@login_required
def search(request):
    id = request.GET.get('q')
    return HttpResponseRedirect(reverse('hq:profile',args=(id,)))

@login_required
def capImg(request,id,name): 

    folder_name = name+"-"+id
    if folder_name not in os.listdir("./media/"):
        os.mkdir("./media/"+folder_name)

    # for i in range(0,6):
    #     try:
    #         ocvgui.App(tkinter.Tk(), "{} {}".format(id,name),video_source = i,path="./media/"+name)
    #         break
    #     except Exception as e:
    #         print(e)
    #         pass
    ocvgui.App(tkinter.Tk(), "{} {}".format(id,name),video_source = WEB_CAM,path="./media/"+folder_name)
    profile_obj = Person.objects.get(id_number=id)
    for x in os.listdir(os.path.join("media",folder_name)):
        obj = PersonImage(person=profile_obj,pictures=os.path.join(folder_name,x))
        obj.save()
    return HttpResponseRedirect(reverse('hq:profile',args=(id,)))

@login_required
def new_entry(request):
    form = forms.PersonBufferForm()
    if request.method == "POST":
        form = forms.PersonBufferForm(request.POST)
        id = request.POST['list_of_people']
        buffer_entry = PersonBuffer.objects.get(id_number=id)
        name = buffer_entry.name
        buffer_entry.delete()

        new_entry = Person(name=name,id_number=id)
        new_entry.save()
        
        return HttpResponseRedirect(reverse('hq:capImg',args=(id,name.replace(' ',''))))

    return render(request,"hq/new_entry_t.html",{"form":form})

@login_required
def profile(request,id):
    
    profile_obj = Person.objects.filter(id_number=id)
    
    if len(profile_obj)==0:
        return render(request,"hq/no_profile.html")

    profile_obj = profile_obj[0]
    profile_image_obj = PersonImage.objects.filter(person=profile_obj)

    return render(request,"hq/profile.html",{"profile_obj":profile_obj,
                                          "profile_image_obj":profile_image_obj})

@login_required
def deleteimg(request,pid,imgid):
    PersonImage.objects.get(id=imgid).delete()
    name = Person.objects.get(id_number=pid).name

    if len(os.listdir(os.path.join("media",name.replace(' ',''))))==0:
        os.rmdir(os.path.join("media",name.replace(' ','')))

    return HttpResponseRedirect(reverse('hq:profile',args=(pid,)))

# @login_required
def gen():
    shm_r = ShmRead('abc')
    while True:
        frame = shm_r.get()
        ret, jpeg = cv2.imencode('.jpg', frame)
        frame =  jpeg.tobytes()
        yield(b'--frame\r\n'
        b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
    #return HttpResponseRedirect(reverse('hq:new_entry'))

# @login_required
@gzip.gzip_page
def startstream(request): 
    try:
        return StreamingHttpResponse(gen(),content_type="multipart/x-mixed-replace;boundary=frame")
    except HttpResponseServerError as e:
        print("aborted")

@login_required
def streamer(request):
        return render(request,"hq/streamer.html")

@login_required
def sync(request):
    #Sync API GOES HERE
    #url = 
    #response = urllib.urlopen(url)

    #JSON RESPONSE Example
    response = {"Vinayak":"200","Mikkal":"123L"}

    for name,id_number in response.items():
        entry = PersonBuffer(id_number=id_number,name=name)
        entry.save()

    return HttpResponseRedirect(reverse('hq:new_entry'))


@login_required
def delete_entry(request,id):
    
    obj = Person.objects.get(id_number=id)
    obj.delete()

    return HttpResponseRedirect(reverse('hq:new_entry'))

@login_required
def edit_entry(request,id):
    
    if request.method == "POST":
        id_new = request.POST.get('id')
        name_new = request.POST.get('name')

        obj = Person.objects.get(id_number=id)
        person = obj
        obj.id_number = id_new
        old_name = obj.name
        obj.name = name_new
        obj.save()
        
        old_folder_name = old_name+"-"+id
        new_folder_name = name_new+"-"+id_new


        try:
            os.rename(os.path.join('media',old_folder_name),os.path.join('media',new_folder_name))
        except:
            pass

        obj = PersonImage.objects.filter(person=person)

        for o in obj:
            url = o.pictures.url.split("/")
            url[2] = new_folder_name
            o.pictures = r"/".join(list(url[2:]))
            o.save()

        return HttpResponseRedirect(reverse('hq:profile',args=(id_new,)))
    
    return render(request,"hq/edit.html",)

templates/hq/index.html
<!DOCTYPE html>
{% load static %}
{% extends "base.html" %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
<style>
    img {
  border-radius: 8px;
  height: auto;
  width: 800px;
}
.wrap-login-custom {
  width: 1000px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
</style>
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('images/bg-01.jpg');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form">
					<span class="login100-form-title p-b-49">
						Facial Recognition System
					</span>

					<div class="wrap-input100 validate-input m-b-23">
						<span class="label-input100">ID Number</span>
						<input class="input100" type="text" name="username" placeholder="ID Number">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<span class="label-input100">Name</span>
						<input class="input100" type="password" name="pass" placeholder="Name">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>
					
					<br><br>
					
					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">
								Create Record
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	
    {% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>


<!-- 
{% load static %}
{% block head_block %}
{% endblock head_block %}
{% block body_block %}
<div class="bg">
    <h3 id="fill">Profile</h3>
    <h4>Name: {{profile_obj.name}}</h4>
    <h5>ID: {{profile_obj.id_number}}</h4><br>
        <a href="{% url 'hq:capImg' profile_obj.id_number profile_obj.name %}" class="btn-del">Add Image</a><br>
    {% for img in profile_image_obj%}
        <img src="{{img.pictures.url}}"><a href="{% url 'hq:deleteimg' profile_obj.id_number img.id %}" class="btn-del">Delete Image</a>
    {% endfor %}

</div>
{% endblock %} -->

templates/hq/new_entry.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block head_block %}
{% endblock head_block %}
{% block body_block %}
<div class="bg">
    <h3 id="fill">New User</h3>
    <div id="form">
        <div class="float_left container">
            <form enctype="multipart/form-data" method="post">
                <div class="block">
                    {% csrf_token %}
                </div>        
                {{ form|crispy }}        
                {% csrf_token %}
                <input type="submit" value="Submit" id="sub">
            </form>
        </div>
    </div>

</div>
{% endblock %}

templates/hq/new_entry_t.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	{% block head_block %}
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
{% endblock head_block %}
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../../static/images/bg-01.jpg');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="POST">
                    {% csrf_token %}
					<span class="login100-form-title p-b-49">
						Facial Recognition System
					</span>
					<a class="success-button" href="{% url 'hq:sync' %}">Sync</a>
					<div class="wrap-input100 validate-input">
                        
                        {{form|crispy}}

					
					
					<br><br>
					
						<div class="container-login100-form-btn">
							<div class="wrap-login100-form-btn">
								<div class="login100-form-bgbtn"></div>
								<button class="login100-form-btn">
									Create Record
								</button>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
	
	{% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>




templates/hq/profile.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	{% block head_block %}
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
<style>
    img {
  border-radius: 8px;
  height: auto;
  width: 800px;
}
.wrap-login-custom {
  width: 1000px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
</style>
{% endblock head_block %}
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../../static/images/bg-01.jpg');">
			<div class="wrap-login-custom  p-l-55 p-r-55 p-t-65 p-b-54">
                <h3>Name: {{profile_obj.name}}</h3> 
				<h3>ID: {{profile_obj.id_number}}</h3>
				<a href="{% url 'hq:delete_entry' profile_obj.id_number %}" class="btn-del">Delete User</a>
				<a href="{% url 'hq:edit_entry' profile_obj.id_number %}" class="btn-del">Edit User</a>
                <br><br>
                <div class="wrap-login100-form-btn">
					<div class="login100-form-bgbtn"></div>
					
                    <button class="login100-form-btn">
                        <a class="login100-form-btn" href="{% url 'hq:capImg' profile_obj.id_number profile_obj.name %}">Add Images</a> 
                    </button>
                </div>
                {% for img in profile_image_obj%}
                <br><br><img src="{{img.pictures.url}}"><br>
                <a href="{% url 'hq:deleteimg' profile_obj.id_number img.id %}" class="btn-del">Delete Image</a>
                {% endfor %}
			</div>
		</div>
	</div>
	
	{% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>

templates/hq/streamer.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
	{% block head_block %}
	<title>Facial Recognition System</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="../../static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animate/animate.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/vendor/select2/select2.min.css">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="../../static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="../../static/css/util.css">
	<link rel="stylesheet" type="text/css" href="../../static/css/main.css">
<!--===============================================================================================-->
<style>
    img {
  border-radius: 8px;
  height: auto;
  width: 800px;
}
.wrap-login-custom {
  width: 1000px;
  background: #fff;
  border-radius: 10px;
  overflow: hidden;
}
</style>
{% endblock head_block %}
</head>
<body>
	{% block body_block %}
	<div class="limiter">
		<div class="container-login100" style="background-image: url('../../static/images/bg-01.jpg');">
			<div class="wrap-login-custom  p-l-55 p-r-55 p-t-65 p-b-54">
                <img src="{% url 'hq:startstream' %}">
			</div>
		</div>
	</div>
	
	{% endblock %}
	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="../../static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/bootstrap/js/popper.js"></script>
	<script src="../../static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/daterangepicker/moment.min.js"></script>
	<script src="../../static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="../../static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="../../static/js/main.js"></script>

</body>
</html>